### ISSUE TITLE
java.lang.IllegalStateException: ApplicationEventMulticaster not initialized error happen when run the project (Error)

### ISSUE THREAD

**Issue by jayamaljayamaha** [EBIvariation/eva-ws#110]
I build the project using maven excluding dgva server and deploy the war file in tomcat and I got following erros

1) java.lang.IllegalStateException: ApplicationEventMulticaster not initialized
2) BeanDefinitionStoreException
3) IllegalStateException: Failed to introspect annotated methods on class org.springframework.boot.web.support.SpringBootServletInitializer
4) NoClassDefFoundError: javax/servlet/ServletContext

and I try this again using different machine and again this error happen. I attached the screan shots and I am not sure whether this is a bug or something wrong in my computer can anyone please look at and configure this??

![Capture](https://user-images.githubusercontent.com/24557887/54735678-8dbf1580-4bcd-11e9-81a5-27a2ea7a7bf1.PNG)
![Capture2](https://user-images.githubusercontent.com/24557887/54735684-931c6000-4bcd-11e9-833a-489f9879a953.PNG)
![Capture3](https://user-images.githubusercontent.com/24557887/54735690-9879aa80-4bcd-11e9-9111-e987b57b285e.PNG)

**Comment by jmmut** [comment]
hi, sorry for the delay. I guess you are not interested anymore, but for the record, although I don't know the exact cause of your problem, these issues of "ClassNotFoundException: ServletContext" usuallly are caused by version incompatibilities. our TravisCI servers work fine with java 8 and we can deploy that in machines with tomcat 8. Anyone else finding this problem can try those versions. At some point we will upgrade versions and will go through the headache of debugging that kind of issues, but not now. Feel free to comment here if you find out what's the exact cause of your issue.

This answer provides other alternatives you could try https://stackoverflow.com/questions/30737617/the-type-javax-servlet-servletcontext-and-javax-servlet-servletexception-cannot

**Comment by tcezard** [comment]
Let us know if you have any other questions
