### ISSUE TITLE
Allow searching by a list of variant identifiers

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/eva-ws#77]
The API currently allows to search by a single variant identifier, but it would be useful for a user to input multiple ones in a single request.

This actually requires changes to several repositories:

1. variation-commons: `VariantRepositoryImpl.findByIdsAndComplexFilters` takes a string parameter which should be replaced by a list. In the test class `VariantRepositoryTest.testCountByIdsAndComplexFilters`, there are only a couple tests searching for a single identifier. They should be extended to support a list. The service built on top of the repository class must also be updated to accept a list.
2. eva-ws: The `variant/info` endpoint should automatically split the identifiers by comma.

**Comment by AdrianBZG** [comment]
Hi, the required changes on variation commons to allow to complete this issue are in the following pull request: [https://github.com/EBIvariation/variation-commons/pull/64](https://github.com/EBIvariation/variation-commons/pull/64)

**Comment by AdrianBZG** [comment]
Hi, actually there's a problem, the /info/ endpoint checks if the given variant ID has the symbol ":" in order to query by coordinates and alleles instead of by ids. Modifying the code to handle the new findByIds function returning a List is straigthforward, but I'm not sure about what to do with the region part (splitting by ":").

Let's say the query is composed of 3 variants, and only one of them has the ":", how I merge a feasible result to return using the query by coord+allels for the first one and the new function for the other 2?

Or maybe, should I only take into account checking for the ":" symbol in case that the given list of variants has actually length 1 (only 1 variant...)??

Thanks.

**Comment by jorizci** [comment]
Hi Adrian, can you post a more concrete example of those queries? I'm a little bit removed from this part of the project and my head is mixing some other API we have.

**Comment by AdrianBZG** [comment]
@jorizci Hi:

Let's go briefly of what the current active implementation of {variantId}/info endpoint does:

- You specify a **single** variantId in the route, such as rs199692280 for instance, and get the corresponding variantEntities: [https://github.com/EBIvariation/eva-ws/blob/develop/eva-server/src/main/java/uk/ac/ebi/eva/server/ws/VariantWSServer.java#L120](https://github.com/EBIvariation/eva-ws/blob/develop/eva-server/src/main/java/uk/ac/ebi/eva/server/ws/VariantWSServer.java#L120) **(Type of variant info query 1)**
- You can specify a chromosome followed by a : symbol which is followed by a region number, e.g. existingChromosome:71822:C:G, this will follow another branch in the endpoint which queries by alleles and coordinates: [https://github.com/EBIvariation/eva-ws/blob/develop/eva-server/src/main/java/uk/ac/ebi/eva/server/ws/VariantWSServer.java#L96](https://github.com/EBIvariation/eva-ws/blob/develop/eva-server/src/main/java/uk/ac/ebi/eva/server/ws/VariantWSServer.java#L96). **(Type of variant info query 2)**

The problem:

- For the type of queries like 1, that **don't** specify any region (: symbol), the new implementation of the corresponding function in Line 120 returns a List, which is correct, we can just call this function with the List of variant Id provided in the query.
- For the type of queries like 2, the function in Line 96 is not returning a List of the variantEntities result that can be composed into a single VariantWithSamplesAndAnnotation to deliver as answer of the query. Thus we need to handle this 2 results separately in the case that now the user queries for something like this list: "existingChromosome:71822:C:G, rs19969228". The problem is that this whole splitted String as List is passed to the new function implementation in L120, but there will be an error since the first variantId is actually a region query, which needs to be handled differently.

We can maybe extract the region queries from the list and do them separately, but then we will have different VariantWithSamplesAndAnnotation objects as result, and we can only return 1.

My question is basically, how should we handle this?

Hope I have explained myself well 😄

**Comment by jorizci** [comment]
Ok, so it is exactly what I had understood from your original message. I'd be on favour of splitting functionality to different endpoints. The problem is the compatibility, as this is only meant to be a small change, not the large refactor that we are thinking for the long term.

I'll discuss it with the rest of the team, but probably it would be for the best maintain current method and create a new rest endpoint that makes the query from proper ids instead of allowing the use of region.

**Comment by AdrianBZG** [comment]
@jorizci Yes, I was thinking of doing that, just creating a separate REST endpoint for querying with a List of variants, without the region feature. Confirm this when you can and I will do it on that way. 😉

**Comment by jorizci** [comment]
@AdrianBZG proceed with the separate REST endpoint. You will also need to modify the old endpoint so that it uses your changes on the variants commons as the function signature has changed. 🙄

**Comment by AdrianBZG** [comment]
@jorizci Great :). For the old endpoint I'll just send a list with 1 element (the variantid) to the new func. definition parameter

**Comment by AdrianBZG** [comment]
@jorizci @cyenyxe I have added the new REST endpoint to search by a list of variant ids (split by ,). Also the old endpoint is preserved and slightly changed to use the new function signatures. Thanks :)
